In [85]:
import traceback
try:
    1/0
except Exception as error:
    aa = traceback.format_exc()
    print(aa)
print(1)

Traceback (most recent call last):
  File "/var/folders/wm/9mwhs7qn1z54jbvm86mnhkbw0000gn/T/ipykernel_69402/3696486459.py", line 3, in <module>
    1/0
ZeroDivisionError: division by zero

1


In [2]:
import numpy as np

In [1]:
from scipy import sparse
from numpy import array
I = array([0,3,1,0])
J = array([0,3,1,2])
V = array([4,5,7,9])
A = sparse.coo_matrix((V,(I,J)),shape=(4,4))

In [2]:
A

<4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in COOrdinate format>

In [5]:
A.transpose

<bound method coo_matrix.transpose of <4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in COOrdinate format>>

In [9]:
np.matmul(A.transpose, A)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [3]:
arr = [1,3,4,5,9]
np.eye(10)[arr]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
import numpy as np
from scipy import sparse
I = np.array([0,0,1,3,3, 1])
J = np.array([0,2,1,3,1,3])
V = np.array([1,1,1,1,1, 1])
B = sparse.coo_matrix((V,(I,J)),shape=(4,5)).tocsr()

In [19]:
B.toarray()

array([[1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0]])

In [20]:
C = B.multiply(B) 

In [21]:
C.toarray()

array([[1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0]])

In [23]:
B.multiply(B.transpose()) 

ValueError: inconsistent shapes

In [33]:
B.toarray()

array([[1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0]])

In [25]:
B.transpose().toarray()

array([[1, 0, 0, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 0]])

In [35]:
C = B.transpose().dot(B).toarray()

In [ ]:
>>> a = np.array([9, 4, 4, 3, 3, 9, 0, 4, 6, 0])
>>> a
array([9, 4, 4, 3, 3, 9, 0, 4, 6, 0])

>>> ind = np.argpartition(a, -4)[-4:]
>>> ind
array([1, 5, 8, 0])

>>> top4 = a[ind]
>>> top4
array([4, 9, 6, 9])

>>> ind[np.argsort(a[ind])]
array([1, 8, 5, 0])


In [52]:
C

array([[1, 0, 1, 0, 0],
       [0, 2, 0, 2, 0],
       [1, 0, 1, 0, 0],
       [0, 2, 0, 2, 0],
       [0, 0, 0, 0, 0]])

In [70]:
C

array([[1, 0, 1, 0, 0],
       [0, 2, 0, 2, 0],
       [1, 0, 1, 0, 0],
       [0, 2, 0, 2, 0],
       [0, 0, 0, 0, 0]])

In [72]:
topk = 5
rating_pred = C
ind = np.argpartition(rating_pred, -topk)
ind = ind[:, -topk:]
arr_ind = rating_pred[np.arange(len(rating_pred))[:, None], ind]
arr_ind_argsort = np.argsort(arr_ind)[np.arange(len(rating_pred)), ::-1]
batch_pred_list = ind[np.arange(len(rating_pred))[:, None], arr_ind_argsort]
batch_pred_list

array([[2, 0, 4, 3, 1],
       [3, 1, 4, 2, 0],
       [2, 0, 4, 3, 1],
       [3, 1, 4, 2, 0],
       [4, 3, 2, 1, 0]])

In [80]:
list(arr_ind[0, :])

[0, 1, 1, 0, 0]

In [51]:
np.argpartition(C, -4)[-4:]

array([[0, 2, 1, 3, 4],
       [1, 3, 2, 0, 4],
       [0, 2, 1, 3, 4],
       [0, 1, 2, 3, 4]])

In [49]:
ind = np.argpartition(C, -5)#axis=-1
ind

array([[1, 0, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [1, 0, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [43]:
ind

array([[1, 3, 2, 0, 4],
       [0, 2, 1, 3, 4],
       [1, 3, 2, 0, 4],
       [0, 2, 1, 3, 4],
       [0, 1, 2, 3, 4]])

In [39]:
top4 = C[ind]

array([[[1, 0, 1, 0, 0],
        [1, 0, 1, 0, 0],
        [0, 2, 0, 2, 0],
        [0, 2, 0, 2, 0],
        [0, 0, 0, 0, 0]],

       [[0, 2, 0, 2, 0],
        [0, 2, 0, 2, 0],
        [1, 0, 1, 0, 0],
        [1, 0, 1, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 0, 1, 0, 0],
        [1, 0, 1, 0, 0],
        [0, 2, 0, 2, 0],
        [0, 2, 0, 2, 0],
        [0, 0, 0, 0, 0]],

       [[1, 0, 1, 0, 0],
        [0, 2, 0, 2, 0],
        [1, 0, 1, 0, 0],
        [0, 2, 0, 2, 0],
        [0, 0, 0, 0, 0]]])

In [78]:
 np.random.normal(0,1,25).reshape(5,5)

array([[ 0.95427113,  0.25236385,  0.32132166, -0.7230696 ,  0.36178314],
       [-0.11550724,  0.80433336, -0.31274696,  0.08892136, -0.9702293 ],
       [ 0.44759289,  0.61014079,  0.37698506,  1.62897944, -0.49212963],
       [-0.2100653 ,  0.32010516,  1.75784466,  0.5411633 , -0.84461986],
       [-0.14519328,  1.79864678, -0.0888354 ,  0.30256225,  0.70608678]])

In [81]:
np.random.normal(0,0.99,10)

array([-0.3672514 ,  1.74653322, -2.41147325, -0.54359275,  1.11371731,
        1.230996  ,  0.48166823, -0.07068976,  1.53157255, -0.32000643])